version: '3.7'

volumes:
  app:
    driver: local
  app_node_modules:
    driver: local

services:
  angular:
    build:
      context: .
    environment:
      - ENV:dev
    ports:
      - "4200:4200"
    volumes:
      - app_node_modules:/app/node_modules
      - .:/app
    command: "node_modules/.bin/ng serve --host 0.0.0.0"
